version: '3'

services:

  node:
    build:
      context: ./client
    container_name: english-quiz-client
    tty: true
    command: "sh -c 'bash /home/client/bin/init.sh'"
    environment:
      TZ: "Asia/Tokyo"
      HOST: "0.0.0.0"
    volumes:
      - ./client:/home/client
    ports:
      - "3000:3000"
    depends_on:
      - php
  
  php:
    build: ./api
    tty: true
    container_name: english-quiz-api
    volumes:
      - ./api:/var/www/html
    environment:
      TZ: Asia/Tokyo
    command: "sh -c 'bash /var/www/html/bin/init.sh && apache2-foreground'"
    ports:
      - "9000:80"
    depends_on:
      - mysql
  
  mysql:
    build: ./database
    container_name: english-db
    ports:
      - "30060:3306"
    volumes:
      - ./database/mysql/mysql.conf:/etc/mysql/mysql.conf
      - ./database/mysql/lib:/var/lib/mysql
      - ./database/mysql/logs:/var/log/database
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
      LC_ALL: "C.UTF-8"
