service: english-quiz-api

provider:
  name: aws
  region: ap-northeast-1
  stage: dev
  runtime: provided.al2
  memorySize: 512
  environment:
    APP_NAME: EnglishQuiz
    APP_ENV: production
    VIEW_COMPILED_PATH: /tmp/storage/framework/views
    APP_STORAGE: '/tmp'

custom:
  defaultStage: dev
  profiles:
    dev: sls-itg
    stg: sls-stg
    prd: sls-prd
  environments: ${file(./config/config.yml)}
  apigwBinary:
    types:
      - multipart/form-data

package:
  exclude:
    - node_modules/**
    - public/storage
    - resources/assets/**
    - storage/**
    - tests/**

functions:
  web:
    handler: public/index.php
    timeout: 120
    layers:
      - ${bref:layer.php-82-fpm}
      - ${bref-extra:gd-php-82}
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'
    environment:
      APP_KEY: ${self:custom.environments.APP_KEY}
      CHAT_GPT_TOKEN: ${self:custom.environments.CHAT_GPT_TOKEN}
      LOG_CHANNEL: ${self:custom.environments.LOG_CHANNEL}
      DB_CONNECTION: ${self:custom.environments.DB_CONNECTION}
      DB_PORT: ${self:custom.environments.DB_PORT}
      DB_HOST: ${self:custom.environments.DB_HOST}
      DB_DATABASE: ${self:custom.environments.DB_DATABASE}
      DB_USERNAME: ${self:custom.environments.DB_USER_NAME}
      DB_PASSWORD: ${self:custom.environments.DB_PASSWORD}
      AWS_URL: ${self:custom.environments.AWS_URL}
      AWS_BUCKET: ${self:custom.environments.AWS_BUCKET}
      AWS_USE_PATH_STYLE_ENDPOINT: ${self:custom.environments.AWS_USE_PATH_STYLE_ENDPOINT}
      MYSQL_ATTR_SSL_CA: ${self:custom.environments.MYSQL_ATTR_SSL_CA}
      SESSION_DRIVER: ${self:custom.environments.SESSION_DRIVER}
      CACHE_DRIVER: ${self:custom.environments.CACHE_DRIVER}
      QUEUE_CONNECTION: ${self:custom.environments.QUEUE_CONNECTION}
      QUEUE_DIRVER: ${self:custom.environments.QUEUE_DIRVER}

  artisan:
    handler: artisan
    timeout: 120
    layers:
      - ${bref:layer.php-82-fpm}
      - ${bref-extra:gd-php-82}
      - ${bref:layer.console}
    environment:
      APP_KEY: ${self:custom.environments.APP_KEY}
      CHAT_GPT_TOKEN: ${self:custom.environments.CHAT_GPT_TOKEN}
      LOG_CHANNEL: ${self:custom.environments.LOG_CHANNEL}
      DB_CONNECTION: ${self:custom.environments.DB_CONNECTION}
      DB_PORT: ${self:custom.environments.DB_PORT}
      DB_HOST: ${self:custom.environments.DB_HOST}
      DB_DATABASE: ${self:custom.environments.DB_DATABASE}
      DB_USERNAME: ${self:custom.environments.DB_USER_NAME}
      DB_PASSWORD: ${self:custom.environments.DB_PASSWORD}
      AWS_URL: ${self:custom.environments.AWS_URL}
      AWS_BUCKET: ${self:custom.environments.AWS_BUCKET}
      AWS_USE_PATH_STYLE_ENDPOINT: ${self:custom.environments.AWS_USE_PATH_STYLE_ENDPOINT}
      MYSQL_ATTR_SSL_CA: ${self:custom.environments.MYSQL_ATTR_SSL_CA}
      SESSION_DRIVER: ${self:custom.environments.SESSION_DRIVER}
      CACHE_DRIVER: ${self:custom.environments.CACHE_DRIVER}
      QUEUE_CONNECTION: ${self:custom.environments.QUEUE_CONNECTION}
      QUEUE_DIRVER: ${self:custom.environments.QUEUE_DIRVER}
    events:
      - schedule:
          rate: cron(0/15 * * * ? *)
          input: '"php artisan queue:work"'

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
